services:
  - type: web
    name: telegram-video-transcoder
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        value: ""  # Add in Render Dashboard
      - key: API_HASH
        value: ""  # Add in Render Dashboard
      - key: BOT_TOKEN
        value: ""  # Add in Render Dashboard
